baseURL = "https://truewebartisans.com"
title   = "True web artisans"

DefaultContentLanguage = "en"

theme = "hello-friend-ng"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

rssLimit  = 10  # Maximum number of items in the RSS feed.
# This message is only used by the RSS template.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License." 

# googleAnalytics = ""
disqusShortname = "1wa"

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = false
buildExpored = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = true
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

GoogleAnalytics  = "53504989"

[permalinks]
  posts = "/posts/:year/:month/:slug/"

[author]
  name = "Vic Shóstak"

[blackfriday]
  hrefTargetBlank = true

[taxonomies]
  tag      = "tags"
  category = "categories"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "Mon, 02 Jan 2006, 15:04 MST"

  # Metadata mostly used in document's head
  description = "The web development team with extensive experience in UX, design, programming, copywriting and business intelligence fields."
  keywords = "web development team, web dev team, online business improve, web development, development team, online business"
  images = [""]

  homeSubtitle = ""

  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  # gitUrl = ""

  # Integrate Javascript files or stylesheets by adding the url to the external assets or by
  # linking local files with their path relative to the static folder, e.g. "css/styles.css"
  customCSS = []
  customJS  = []

  # Toggle this option need to rebuild SCSS, requires extended version of Hugo
  justifyContent = false  # Set "text-align: justify" to .content.

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "dark"
  themeColor = "#252627"

  [params.logo]
    path = "/images/webartisans-logo-full-white.svg"
    alt = "true web artisans logo"
    logoHomeLink = "/"

  # Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/intent/follow?screen_name=true_koddr"

  [[params.social]]
    name = "email"
    url  = "mailto:truewebartisans@gmail.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/koddr"

  [[params.social]]
    name = "instagram"
    url  = "https://www.instagram.com/true_webartisans/"

[languages]
  [languages.en]
    subtitle  = "The web development team, which always thinks about your online business"
    weight    = 1
    copyright = '<a href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank" rel="noopener">CC BY-NC-ND 4.0</a>'
    languageName = "English"

  [languages.ru]
    subtitle  = "Команда веб-разработчиков, которая всегда думает о вашем онлайн-бизнесе"
    weight    = 2
    copyright = '<a href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank" rel="noopener">CC BY-NC-ND 4.0</a>'
    languageName = "Русский"

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "posts/"
