# docker-compose.prod.yml by Vic Shóstak <truewebartisans@gmail.com> (https://1wa.co)

version: "3.7"

services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    volumes:
      - /static:/frontend/dist

  nginx:
    volumes:
      - ./webserver/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./webserver/nginx/1wa.co.conf:/etc/nginx/sites-enabled/1wa.co.conf
      - ./webserver/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./webserver/certbot/conf:/etc/letsencrypt
      - ./webserver/certbot/www:/var/www/certbot
      - /static:/usr/share/nginx/html
    ports:
      - 80:80
      - 443:443
    depends_on:
      - frontend
