name: Deploy via SSH

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      # Build eleventy
      - name: Build eleventy
        uses: TartanLlama/actions-eleventy@master
        with:
          install_dependencies: true

      # Copy to remote server
      - name: Copy build files via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          rm: true
          source: "dist/*.*"
          target: "${{ secrets.REMOTE_DIR }}"
